development:
  adapter: postgresql
  encoding: unicode
  database: gem-ratings_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: gem-ratings_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: gem-ratings_production
  pool: 5
